name: CI/CD on GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up NodeJS
        uses: actions/setup-node@v2
      
      - name: Install dependencies
        run: npm install
      
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2

      - name: Deploy to GCP VM via SSH
        run: |
          echo "Deploying to GCP VM..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ci-cd-gcp
          chmod 600 ci-cd-gcp
          sudo ssh -i ci-cd-gcp -o StrictHostKeyChecking=no root@${{ secrets.GCP_VM_IP }} cd /home/ubuntu && sudo apt update && git pull && npm install && npm run build && pm2 restart all
