name: CI/CD on GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: myenvironment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up NodeJS
        uses: actions/setup-node@v2
      
      - name: Install dependencies
        run: npm install
      
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GCP VM via SSh
        run: |
          echo "Deploying to GCP VM..."
          echo "HERE ${{ secrets.SSH_PRIVATE_KEY }} it is the secret key"
          ssh -i b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACCzrgohAV/t8IlSKd4cYN1n/F+z1x9MdSXleh0GtpG87QAAAJBFmsn6RZrJ+gAAAAtzc2gtZWQyNTUxOQAAACCzrgohAV/t8IlSKd4cYN1n/F+z1x9MdSXleh0GtpG87QAAAECq5BNUizZpgtJ5iGZwd+ckcszRo7OEZ9EDCn6lfHCQ2bOuCiEBX+3wiVIp3hxg3Wf8X7PXH0x1JeV6HQa2kbztAAAAC3Jvb3RASGFyaXNoAQI=@35.225.238.96
          mkdir app
          cd app
          