name: CI/CD on GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_SSH_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            git clone https://github.com/Harishharris/ci-cd-gcp.git app
            cd app
            sudo kill -9 $(ps -e | grep node | awk '{print $1}') 2>/dev/null || true
            npm install
            pm2 start app.js
            exit 0
